export { default as AboutTheCompany } from "./AboutTheCompany"
export { default as Blog } from "./Blog"
export { default as CompanyPanel } from "./CompanyPanel"
export { default as ServicesAndFees } from "./ServicesAndFees"
export { default as Team } from "./Team"
export { default as Values } from "./Values"